<template>
  <div>
    <h1>home</h1>
    <p>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    </p>
    <p>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    </p>
    <p>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    </p>
    <p>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    </p>
    <p>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    </p>
  </div>
</template>

<script>
export default {
  name: 'home'
}
</script>

<style scoped>
</style>
